#!/bin/bash

xrandr --output HDMI-A-0 --rate 60 --rotate left --mode 1920x1080 --pos 0x0
xrandr --output DisplayPort-1 --rate 143.98 --primary --mode 1920x1080 --pos 1080x615
xrandr --output HDMI-A-1 --rate 143.98 --mode 1920x1080 --pos 3000x615
